[project]
name = "desk-control"
version = "0.1.0"
description = ""
authors = [
    {name = "JorgenKrieger",email = "jorgen@labelnoir.me"}
]
license = "MIT"
requires-python = ">=3.11"
dependencies = [
    "bleak (>=3.0.2,<4.0.0)",
    "fastapi (>=0.141.1,<0.142.0)",
    "uvicorn (>=0.52.4,<0.53.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
